### ISSUE TITLE
Module/include cells

### ISSUE THREAD

**Issue by emmaccode** [ChifiSource/Olive.jl#28]
I would like to have a stacking module system in each window, where modules are added to the tab container as new tabs which can be edited individually. This will be post `IPyCells` `0.1.1` because I'll need a split ends function.
Anyway this will just make it easier to work with modules and included files in olive.it will be pretty easy I just make a new `Project{:module}` type, populate it when the cell is ran. The module cell contains cells of its own then I write a `string` function that turns it into a normal module. 
**The hardest part of this will be getting cells out of the reader**. Will need to find all of the modules and then sort the cells that belong into those modules properly into the modules.

**Comment by emmettgb** [comment]
Include cells have a partial implementation, will soon be added along with module cells :) better project structure and organization, etc.

**Comment by emmaccode** [comment]
closed by #94 ! :')
